name: Build and Push
on: [push]

jobs:
  build-push:
    runs-on: ubuntu-22.04
    container:
      image: quay.io/buildah/stable:latest
    
    env:
      BUILDAH_ISOLATION: chroot
      _BUILDAH_STARTED_IN_USERNS: ""
      
    steps:
      - name: Debug curl
        run: |
          curl --version
          curl -v6 http://git.s.hetmer.net
          curl -v http://git.s.hetmer.net
      - name: Checkout
        run: |
          SERVER=http://git.s.hetmer.net
          git clone "${SERVER//:\/\//://${{ github.actor }}:${{ secrets.FORGEJO_TOKEN }}@}/${{ github.repository }}.git" "${GITHUB_WORKSPACE}"

      - name: Build and Push
        run: |
          DOMAIN=git.hetmer.net
          DOMAIN="${DOMAIN#*//}"
          REPO="${{ github.repository }}"
          IMAGE="${DOMAIN}/${REPO,,}:latest"

          # Tell buildah this registry is insecure (HTTP only)
          #mkdir -p /etc/containers
          #cat > /etc/containers/registries.conf.d/insecure.conf <<EOF
          #[[registry]]
          #location = "${DOMAIN}"
          #insecure = true
          #EOF

          buildah login -u "${{ github.actor }}" -p "${{ secrets.FORGEJO_TOKEN }}" "${DOMAIN}"
          buildah bud -t "${IMAGE}" .
          buildah push "${IMAGE}"
