name: Build and Push
on: [push]

jobs:
  build-push:
    runs-on: ubuntu-22.04
    container:
      image: quay.io/buildah/stable:latest
    
    env:
      BUILDAH_ISOLATION: chroot
      _BUILDAH_STARTED_IN_USERNS: ""

    steps:
      - name: Checkout
        run: |
          SERVER=http://git.s.hetmer.net
          git clone "${SERVER//:\/\//://${{ github.actor }}:${{ secrets.FORGEJO_TOKEN }}@}/${{ github.repository }}.git" "${GITHUB_WORKSPACE}"

      - name: Build and Push
        run: |
          DOMAIN=git.hetmer.net
          REPO="${{ github.repository }}"
          IMAGE="${DOMAIN}/${REPO,,}:latest"

          buildah login -u "${{ github.actor }}" -p "${{ secrets.FORGEJO_TOKEN }}" "${DOMAIN}"
          buildah bud --label "org.opencontainers.image.source=https://${DOMAIN}/${{ github.repository }}" -t "${IMAGE}" .
          buildah push --jobs 1 "${IMAGE}"