name: Build and Push
on: [push]

jobs:
  build-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Push
        run: |
          DOMAIN=git.hetmer.net
          IMAGE="${DOMAIN}/${{ github.repository,,}}:latest"
          echo "${{ secrets.CI_REGISTRY_PUSH }}" | docker login "${DOMAIN}" -u "${{ github.actor }}" --password-stdin
          docker buildx build \
            --label "org.opencontainers.image.source=https://${DOMAIN}/${{ github.repository }}" \
            --push \
            -t "${IMAGE}" .